max_jobs: 1
version: v2-{build}-for-windows
skip_branch_with_pr: true
skip_non_tags: true
environment:
  matrix:
  - nodejs_version: "12"
platform:
  - x64
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
clone_folder: c:\project
cache:
  - node_modules
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install -g yarn
before_build:
  - cd c:\project\starbeat-core
  - yarn install
  - cd c:\project\starbeat-client
  - del package.json
  - rename package-windows.json package.json
  - yarn install
  - cd c:\project
  - yarn install
build_script:
  - cd c:\project\starbeat-core
  - yarn build
  - xcopy c:\project\starbeat-core\build c:\project\starbeat-client\build /s/y
  - cd c:\project\starbeat-client
  - yarn pack:win
after_build:
  - cd c:\project
  - node build-win.js
  - cd release
  - rename Setup.exe Tongfang-Hackintosh-Utility-Windows-Setup.exe
artifacts:
  - path: release\Tongfang-Hackintosh-Utility-Windows-Setup.exe
    name: setup
deploy:
  - provider: GitHub
    artifact: setup
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
    auth_token:
      secure: hCeYMHCYlNMskb+nhK5TcbzquabXYRgrWjlQD9R2bCimADhVae3Rkz9SqWp2sJV2